services:
  # minecraft-discord-bot:
  #   build: .
  #   container_name: minecraft-discord-bot
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   user: root
  #   environment:
  #     CONTAINER_NAME: ${CONTAINER_NAME}
  #     DISCORD_TOKEN: ${DISCORD_TOKEN}
  #     GUILD_ID: ${GUILD_ID}
  #     DATABASE_URL: ${DATABASE_URL}
  #     SQLX_OFFLINE: ${SQLX_OFFLINE}
  #     LOG_LEVEL: "trace"
  #   env_file:
  #     - .env

  mc:
    image: itzg/minecraft-server
    container_name: minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERRSION: 1.21.10
      PAPER_BUILD: 113

  # testing-container:
  #   container_name: testing-container
  #   image: alpine
  #   command: 
  #     - /bin/sh
  #     - -c
  #     - |
  #       i=0
  #       while true; do
  #         echo $$i
  #         echo "[20:41:25 INFO]: sally joined the game"
  #         i=$((i+1))
  #         sleep 1
  #       done

  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 10000:8080
